site_name: Nico's sample docsite
site_url: https://nicoalba.github.io/docsite-apis/
site_dir: site
theme: 
  name: ivory
  palette: 
    - scheme: slate
      primary: orange
      accent: orange
  features:
    - navigation.path
    - content.code.copy
    - content.code.annotate
extra_javascript:
  - https://cdn.redoc.ly/redoc/v2.0.0-rc.74/bundles/redoc.standalone.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - redoc-tag:
      spec_path: api/chess-api.yml

nav:
  - Overview: index.md
  - Get started: get-started.md
  - Tutorials:
    - Retrieve player history: tutorial/retrieve-player-game-history
  - Concepts:
    - Concepts 1: concepts/concept-1.md
  - Reference:
    - API docs: api/api-docs.md
    - Example code: reference/example-code.md
    - Definitions: reference/definitions.md
    - Data tables: reference/data-tables.md