site_name: Sample docsite
theme: 
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: orange
      accent: orange

      

nav:
  - Overview: index.md
  - Get started: get-started.md
  - Tutorials:
    - Tutorial 1: tutorial-1.md
  - Reference:
    - Reference 1: reference-1.md